import = ["/Users/victor/.config/alacritty/themes/iterm.toml"]

[colors]
draw_bold_text_with_bright_colors = true

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.bold]
family = "CaskaydiaCove Nerd Font"
style = "Bold"

[font.bold_italic]
family = "CaskaydiaCove Nerd Font"
style = "Bold Italic"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "CaskaydiaCove Nerd Font"
style = "Italic"

[font.normal]
family = "CaskaydiaCove Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0

[mouse]
hide_when_typing = false

[scrolling]
history = 10000
multiplier = 3

[window]
decorations = "none"
dynamic_padding = false
opacity = 0.95
startup_mode = "Maximized"

[window.dimensions]
columns = 120
lines = 80

[window.padding]
x = 10
y = 15
